### ISSUE TITLE
Link to nanopub monitor broken

### ISSUE THREAD

**Issue by culturetogo** [tkuhn/nanopub-server#16]
Hi,

This repo seems to need a bit of housekeeping: The link to the nanopublication servers monitor (http://app.tkuhn.eculture.labs.vu.nl/nanopub-monitor/) is broken and should be https://monitor.np.trustyuri.net/ (?)

Best, Michael

**Comment by tkuhn** [comment]
Hi Michael,

You are right. I just updated the links for the monitor and the servers. Thanks for reporting!

Regards,
Tobias

**Comment by culturetogo** [comment]
Great, thanks. And congratulations on the fantastic work you are doing with your nanopublications ecosystem!

**Comment by tkuhn** [comment]
Thanks! :)

btw, if you would like to stay up-to-date with respect to developments around nanopublications, you might want to subscribe to this mailing list: https://groups.google.com/g/nanopub-users/
