### ISSUE TITLE
Add JSONLD support

### ISSUE THREAD

**Issue by raffazizzi** [tkuhn/nanopub-server#2]
JSONLD is supported by Rio. Indeed, adding "application/ld+json" to https://github.com/tkuhn/nanopub-server/blob/master/src/main/java/ch/tkuhn/nanopub/server/NanopubPage.java#L63

enables JSONLD retrieval when the URL is requested with the proper content type.

It doesn't seem to be possible to require JSON-LD based on the file extension, however. This line returns null when passed "jsonld". https://github.com/tkuhn/nanopub-server/blob/master/src/main/java/ch/tkuhn/nanopub/server/NanopubPage.java#L57

**Comment by tkuhn** [comment]
Resolved with commit 66ed7d47b9c4f16b639a5b769bdad30006c07ce7

http://np.inn.ac server is updated and now supports JSON-LD.
