### ISSUE TITLE
NP Monitor is down

### ISSUE THREAD

**Issue by AlasdairGray** [tkuhn/nanopub-server#6]
The [Nanopub monitor](http://npmonitor.inn.ac/) and the [example np server](http://np.inn.ac/) linked in the README are not responding.

**Comment by tkuhn** [comment]
Yes, I know. The server is not under my control. I hope it will come back. But you can in any case use this [monitor](http://app.tkuhn.eculture.labs.vu.nl/nanopub-monitor/) and use the other servers in the network.

**Comment by tkuhn** [comment]
Perfect, thanks!
